//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.20 at 11:10:41 AM BRT 
//


package br.com.deere.john.exercisesoap.soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for cResultadoModal complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cResultadoModal"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ServicosModal" type="{http://tempuri.org/}ArrayOfCModal" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cResultadoModal", propOrder = {
    "servicosModal"
})
public class CResultadoModal {

    @XmlElement(name = "ServicosModal")
    protected ArrayOfCModal servicosModal;

    /**
     * Gets the value of the servicosModal property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfCModal }
     *     
     */
    public ArrayOfCModal getServicosModal() {
        return servicosModal;
    }

    /**
     * Sets the value of the servicosModal property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfCModal }
     *     
     */
    public void setServicosModal(ArrayOfCModal value) {
        this.servicosModal = value;
    }

}
